// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ATSBeginSession(arg1) {
  return window['go']['main']['App']['ATSBeginSession'](arg1);
}

export function ATSInterviewFind(arg1) {
  return window['go']['main']['App']['ATSInterviewFind'](arg1);
}

export function ATSInterviewList() {
  return window['go']['main']['App']['ATSInterviewList']();
}

export function ATSLogin(arg1, arg2) {
  return window['go']['main']['App']['ATSLogin'](arg1, arg2);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GenerateQuestionBank(arg1) {
  return window['go']['main']['App']['GenerateQuestionBank'](arg1);
}

export function GetQuestionBank(arg1) {
  return window['go']['main']['App']['GetQuestionBank'](arg1);
}

export function ListAudioDevices() {
  return window['go']['main']['App']['ListAudioDevices']();
}

export function ManualEvaluateAnswer() {
  return window['go']['main']['App']['ManualEvaluateAnswer']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function SaveFiles(arg1, arg2) {
  return window['go']['main']['App']['SaveFiles'](arg1, arg2);
}

export function StartRecording(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2, arg3);
}

export function StartSession(arg1, arg2) {
  return window['go']['main']['App']['StartSession'](arg1, arg2);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function WorkableEventFind(arg1) {
  return window['go']['main']['App']['WorkableEventFind'](arg1);
}

export function WorkableInterviewList(arg1) {
  return window['go']['main']['App']['WorkableInterviewList'](arg1);
}
