// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function InferNextQuestion(arg1:string,arg2:string):Promise<Record<string, string>>;

export function ListAudioDevices():Promise<main.ListSourcesResonse>;

export function Minimize():Promise<void>;

export function SaveFiles(arg1:string,arg2:string):Promise<string>;

export function StartRecording(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopRecording():Promise<void>;
