// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {atsclient} from '../models';
import {main} from '../models';
import {adkutils} from '../models';

export function ATSBeginSession(arg1:string):Promise<string>;

export function ATSInterviewFind(arg1:string):Promise<atsclient.InterviewFindResult>;

export function ATSInterviewList():Promise<Array<atsclient.InterviewListItem>>;

export function ATSLogin(arg1:string,arg2:string):Promise<atsclient.LoginResponse>;

export function Close():Promise<void>;

export function ListAudioDevices():Promise<main.ListSourcesResonse>;

export function ManualEvaluateAnswer():Promise<string>;

export function Minimize():Promise<void>;

export function SaveFiles(arg1:string,arg2:string):Promise<string>;

export function StartRecording(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartSession(arg1:string,arg2:Array<adkutils.QuestionBankQuestion>):Promise<string>;

export function StopRecording():Promise<void>;
