// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {atsclient} from '../models';
import {main} from '../models';
import {adkutils} from '../models';
import {workableclient} from '../models';

export function ATSBeginSession(arg1:string):Promise<string>;

export function ATSCheckGoogleDriveAuthorization():Promise<atsclient.DriveAuthStatus>;

export function ATSInterviewFind(arg1:string):Promise<atsclient.InterviewFindResult>;

export function ATSInterviewList():Promise<Array<atsclient.InterviewListItem>>;

export function ATSLogin(arg1:string,arg2:string):Promise<main.AppLoginResponse>;

export function ATSUploadSessionToDrive(arg1:string):Promise<atsclient.DriveUploadFolderResponse>;

export function BeginSession(arg1:string):Promise<string>;

export function Close():Promise<void>;

export function GenerateQuestionBank(arg1:string,arg2:string):Promise<string>;

export function GetQuestionBank(arg1:string):Promise<Array<adkutils.QuestionBankQuestion>>;

export function HasQuestionBank(arg1:string):Promise<boolean>;

export function ListAudioDevices():Promise<main.ListSourcesResonse>;

export function ManualEvaluateAnswer():Promise<string>;

export function Minimize():Promise<void>;

export function SaveFiles(arg1:string,arg2:string):Promise<string>;

export function StartRecording(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartSession(arg1:string,arg2:Array<adkutils.QuestionBankQuestion>):Promise<string>;

export function StopRecording():Promise<void>;

export function WorkableCandidateCommentCreate(arg1:string,arg2:string,arg3:string):Promise<workableclient.Comment>;

export function WorkableEventFind(arg1:string):Promise<workableclient.EventFindResult>;

export function WorkableInterviewList(arg1:string):Promise<Array<workableclient.Event>>;
