// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function SaveFiles(arg1, arg2) {
  return window['go']['main']['App']['SaveFiles'](arg1, arg2);
}

export function StartRecording(arg1, arg2) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
